# Generated by Django 3.1.5 on 2021-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', help_text='原始文本', max_length=5000, verbose_name='原始文本')),
                ('pre_text', models.TextField(default='', help_text='预处理文本', max_length=5000, verbose_name='预处理文本')),
                ('predict_tag', models.CharField(default='', help_text='预测标签', max_length=30, verbose_name='预测标签')),
                ('human_tag', models.CharField(default='', help_text='人工打标签', max_length=30, verbose_name='人工打标签')),
                ('pending_tag', models.BooleanField(default=False, help_text='待定标记', verbose_name='待定标记')),
            ],
        ),
    ]
